#
# Marlin Firmware
# PlatformIO Configuration File
#

#################################
#
# STM32G0 Architecture
#
# Naming Example: STM32G474RET6
#
#   G : Foundation
#   4 : Cortex M4 core (0:M0, 1-2:M3, 3-4:M4, 7:M7)
#   R : 64 pins  (R:64 or 66, F:20)
#   E : 512KB Flash-memory  (B:128KB C:256KB, D:384KB, E:512KB, G:1024KB)
#   T : LQFP package
#   6 : -40...85°C   (7: ...105°C)
#
#################################

#
# nucleo_G474RE (STM32G474RET6 ARM Cortex-M0+)
#
[env:nucleo_G474RE]
extends                     = stm32_variant
platform                    = ststm32@~14.1.0
platform_packages           = framework-arduinoststm32@https://github.com/stm32duino/Arduino_Core_STM32/archive/main.zip
                              toolchain-gccarmnoneeabi@1.100301.220327
board                       = nucleo_G474RE
board_build.offset          = 0x8000
board_upload.offset_address = 0x08008000
build_flags                 = ${stm32_variant.build_flags}
                              -DPIN_SERIAL1_RX=PA_10 -DPIN_SERIAL1_TX=PA_9
                              -DSERIAL_RX_BUFFER_SIZE=1024 -DSERIAL_TX_BUFFER_SIZE=1024
                              -DTIMER_SERVO=TIM3 -DTIMER_TONE=TIM4
                              -DSTEP_TIMER_IRQ_PRIO=0
upload_protocol             = stlink
debug_tool                  = stlink