#
# Marlin Firmware
# PlatformIO Configuration File
#

#################################
#
# STM32F7 Architecture
#
# Naming Example: STM32F767ZIT6
#
#   F : Foundation (sometimes High Performance F2/F4)
#   7 : Cortex M7 core (0:M0, 1-2:M3, 3-4:M4, 7:M7)
#  67 : Line/Features
#   Z : 144 pins
#   I : 4096KB Flash-memory
#   T : LQFP package
#   6 : -40...85°C   (7: ...105°C)
#
#################################

#
# ST NUCLEO-F767ZI Development Board
# This environment is for testing purposes prior to control boards
# being readily available based on STM32F7 MCUs
#
[env:NUCLEO_F767ZI]
extends       = common_stm32
board         = nucleo_f767zi
build_flags   = ${common_stm32.build_flags} -DTIMER_SERIAL=TIM9



#
# ST NUCLEO-F746ZG Development Board
# This environment is for testing purposes prior to control boards
# being readily available based on STM32F7 MCUs
#
# Loads at 0x08000000
#
[env:NUCLEO_F746ZG]
extends       = common_stm32
board         = nucleo_f746zg
build_flags   = ${common_stm32.build_flags} -DTIMER_SERIAL=TIM9
                -DUSE_USB_FS
        -DUSBCON
                -DUSBD_USE_CDC



[common_stm32_no_usb]
#platform         = ststm32@~12.1
platform         = ststm32
board_build.core = stm32
build_flags      = ${common.build_flags} -std=gnu++14
                   -DHAL_STM32 -DPLATFORM_M997_SUPPORT
                   -DTIM_IRQ_PRIO=13 -DADC_RESOLUTION=12
#                   -DUSBCON -DUSBD_USE_CDC
build_unflags    = -std=gnu++11
build_src_filter = ${common.default_src_filter} +<src/HAL/STM32> -<src/HAL/STM32/tft> +<src/HAL/shared/backtrace>
extra_scripts    = ${common.extra_scripts}
                   pre:buildroot/share/PlatformIO/scripts/stm32_serialbuffer.py




#
# ST NUCLEO-F746ZG Development Board
# This environment is for testing purposes prior to control boards
# being readily available based on STM32F7 MCUs
#
# Loads at 0x08000000 + VECTOR_TABLE_OFFSET.
#
[env:NUCLEO_F746ZG_WITH_BOOTLOADER]
extends       = common_stm32
board         = nucleo_f746zg
build_flags   = ${common_stm32.build_flags} -DTIMER_SERIAL=TIM9
# point USART3 at ST Link virtual com port
                 -DPIN_SERIAL3_RX=PD9
                 -DPIN_SERIAL3_TX=PD8
                 -DVECT_TAB_OFFSET=0x8000  # must be same as bootloader offset
                 -O0
#                 -DLD_FLASH_OFFSET=0x8000
#                 -Wl,--defsym,LD_FLASH_OFFSET=0x00008000
#                 -Wl,--defsym,LD_FLASH_OFFSET,0x8000  # syntax error
#                 -Wl,--defsym,LD_FLASH_OFFSET=0x8000  # symbol defined but value is 0
#                 -Wl,--defsym=LD_FLASH_OFFSET=0x8000  # symbol defined but value is 0
#                 -Wl,--defsym LD_FLASH_OFFSET=0x8000  #LD_FLASH_OFFSET=0x8000' not found, needed by target `
#                 -Wl,-_LD_FLASH_OFFSET=0x8000 # unrecognized option
#                 -Wl,_LD_FLASH_OFFSET=0x8000  # no such file or directory
#                 -Wl,LD_FLASH_OFFSET=0x8000  # no such file or directory
#                 -Wl,-LD_FLASH_OFFSET=0x8000 # no effect
#                 -Wl,--defsym=LD_FLASH_OFFSET=0x8000 # no effect
#                 -Wl,--LD_FLASH_OFFSET=0x8000  # unkown option
#       -DLD_FLASH_OFFSET=0x8000
#board_build.offset = 0x10000
# load offset is set in the ldscript
#LDFLAGS = -Wl,--LD_FLASH_OFFSET=0x8000
#LDFLAGS = -Wl,--defsym=LD_FLASH_OFFSET=0x8000
#LDFLAGS = -Wl,-LD_FLASH_OFFSET=0x8000
#
board_build.ldscript = Marlin/src/HAL/STM32/STM32F7/STM32F7xx_boot_ldscript.ld
#extra_scripts    = buildroot/share/PlatformIO/scripts/offset_and_rename.py
#build.offset     = 0x8000

#
# REMRAM_V1
#
[env:REMRAM_V1]
extends       = common_stm32
board         = remram_v1
